const state={session:`demo-${Date.now()}`,catalog:null,tab:'intents',preview:null,currentQuery:'',lastDecision:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const API_BASE=location.protocol==='file:'?'http://127.0.0.1:8000':'';
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function api(path,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(`${API_BASE}${path}`,{headers:{'Content-Type':'application/json'},signal:controller.signal,...options});const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{throw Error(`服务返回格式异常（HTTP ${r.status}）`)}if(!r.ok)throw Error(d.error||`请求失败（HTTP ${r.status}）`);return d}catch(e){if(e.name==='AbortError')throw Error('请求超时，请确认 Ontology Runtime 已启动');if(e instanceof TypeError)throw Error('无法连接 Ontology Runtime，请启动本地服务后重试');throw e}finally{clearTimeout(timer)}}
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
const meta={chat:['智能客服','以业务对象和证据驱动每一次回答与操作'],reviews:['人工审核','高风险动作的人机协同控制台'],ontology:['本体配置','把业务语义沉淀为可运行的能力'],operations:['运营审计','全链路可观测、可回放、可追责']};

$$('.nav').forEach(b=>b.onclick=()=>{const v=b.dataset.view;$$('.nav,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${v}`).classList.add('active');$('#title').textContent=meta[v][0];$('#subtitle').textContent=meta[v][1];if(v==='reviews')loadReviews();if(v==='ontology')loadCatalog();if(v==='operations')loadOps()});
const scroll=()=>{$('#messages').scrollTop=$('#messages').scrollHeight};
function addUser(text){$('#messages').insertAdjacentHTML('beforeend',`<div class="message user"><div><p>${esc(text)}</p></div></div>`);scroll()}
function addLoading(){const id=`wait-${Date.now()}`;$('#messages').insertAdjacentHTML('beforeend',`<div class="message bot" id="${id}"><b>曜</b><div><p>正在读取业务对象与规则…</p></div></div>`);scroll();return id}
function addAnswer(d){const tools=d.tool_results||[],evidence=d.evidence||[],intent=d.intent||{};let extra='';if(tools.length)extra=`<div class="result"><strong>已调用 ${tools.length} 个业务工具</strong><div>${tools.slice(0,3).map(x=>`<span class="tag">${esc(x.tool)}</span>`).join('')}</div>${evidence[0]?`<div class="evidence"><span>${esc(evidence[0].title)}</span><span>v${esc(evidence[0].version)}</span></div>`:''}</div>`;if(d.action)extra+=`<div class="action"><em>${esc(d.risk)} · ${d.action.review_required?'需人工审核':'需用户确认'}</em><h4>${esc(d.action.label)}</h4><small>${esc((d.action.preconditions||[]).join(' · '))}</small><button data-action="${d.action.id}">${d.action.review_required?'确认提交审核':'确认执行'}</button></div>`;$('#messages').insertAdjacentHTML('beforeend',`<div class="message bot"><b>曜</b><div><p>${esc(d.response||'本轮处理已完成，但未生成回答。')}</p>${extra}<small>${esc(intent.level1||'未分类')} / ${esc(intent.level2||'未分类')} · 置信度 ${((intent.confidence||0)*100).toFixed(0)}%</small></div></div>`);scroll();$$('[data-action]').forEach(x=>x.onclick=()=>confirmAction(x))}
function addError(message){$('#messages').insertAdjacentHTML('beforeend',`<div class="message bot error-message"><b>!</b><div><p>${esc(message)}</p><small>请确认后端服务运行在 127.0.0.1:8000，然后重试</small></div></div>`);scroll()}

let previewTimer=0,previewSequence=0;
function traceRows(rows,status='preview'){ $('#traceEmpty').style.display='none';$('#traceBody').innerHTML=rows.map((x,i)=>`<div class="step ${i===0?status:''}" data-step="${i}" role="button" tabindex="0"><b>${i+1}</b><div><strong>${x[0]}</strong><small>${i===0?(status==='preview'?'已预识别':'处理中'):'等待'}</small><p>${esc(x[1])}</p></div></div>`).join('') }
const genericSteps=p=>[['意图识别',p?`${p.intent.level1} / ${p.intent.level2} · ${(p.intent.confidence*100).toFixed(0)}%`:'分析用户表达与上下文'],['绑定业务能力',p?`${p.capability.name} · ${p.capability.id}`:'等待意图确认'],['读取业务对象','解析客户、车辆、订单等实体'],['执行 Functions','调用只读业务工具'],['检索证据','按对象范围检索知识'],['规则与风险','计算风险等级与动作边界'],['生成响应','组合事实、证据与下一步动作']];
async function previewIntent(text){const seq=++previewSequence,box=$('#intentPreview');state.currentQuery=text;if(text.length<2){state.preview=null;box.className='intent-preview';box.innerHTML='<span class="preview-dot"></span><span>输入问题后自动识别意图</span>';return}box.className='intent-preview loading';box.innerHTML='<span class="preview-dot"></span><span>正在预识别意图…</span>';try{const p=await api('/api/intent/preview',{method:'POST',body:JSON.stringify({message:text})});if(seq!==previewSequence)return;state.preview=p;box.className='intent-preview recognized';box.innerHTML=`<span class="preview-dot"></span><strong>${esc(p.intent.level1)} / ${esc(p.intent.level2)}</strong><span>置信度 ${(p.intent.confidence*100).toFixed(0)}% · ${esc(p.capability.name)}</span>`;$('#traceId').textContent='意图预识别';traceRows(genericSteps(p),'preview')}catch(e){if(seq===previewSequence){state.preview=null;box.className='intent-preview';box.innerHTML='<span class="preview-dot"></span><span>预识别服务暂不可用，提交后继续处理</span>'}}}
$('#input').addEventListener('input',e=>{clearTimeout(previewTimer);previewTimer=setTimeout(()=>previewIntent(e.target.value.trim()),260)});
async function animateTrace(preview){const rows=genericSteps(preview);traceRows(rows,'running');$('#traceId').textContent='决策执行中';for(let i=0;i<rows.length;i++){const current=$(`.step[data-step="${i}"]`);current.className='step running';current.querySelector('small').textContent='处理中';await sleep(210);current.className='step done';current.querySelector('small').textContent='完成'}}
$('#chatForm').onsubmit=async e=>{e.preventDefault();const input=$('#input'),text=input.value.trim();if(!text)return;state.currentQuery=text;addUser(text);input.value='';const id=addLoading(),animation=animateTrace(state.preview);try{const request=api('/api/chat',{method:'POST',body:JSON.stringify({session_id:state.session,user_id:'C1001',message:text})});const [d]=await Promise.all([request,animation]);state.lastDecision=d;$(`#${id}`)?.remove();renderTrace(d);addAnswer(d);updateBadge();$('#intentPreview').className='intent-preview recognized';$('#intentPreview').innerHTML=`<span class="preview-dot"></span><strong>${esc(d.intent.level1)} / ${esc(d.intent.level2)}</strong><span>最终置信度 ${(d.intent.confidence*100).toFixed(0)}%</span>`}catch(err){$(`#${id}`)?.remove();addError(err.message);toast(err.message)}};
$$('.chips button').forEach(b=>b.onclick=()=>{$('#input').value=b.textContent;previewIntent(b.textContent);$('#chatForm').requestSubmit()});
$('#reset').onclick=()=>{state.session=`demo-${Date.now()}`;state.preview=null;state.lastDecision=null;state.currentQuery='';$('#messages').innerHTML='<div class="message bot"><b>曜</b><div><p>新会话已创建。你想查询什么？</p><small>上下文已清空</small></div></div>';$('#traceBody').innerHTML='';$('#traceEmpty').style.display='grid';$('#traceId').textContent='等待请求';$('#intentPreview').className='intent-preview';$('#intentPreview').innerHTML='<span class="preview-dot"></span><span>输入问题后自动识别意图</span>'};
async function confirmAction(b){b.disabled=true;try{const d=await api(`/api/actions/${b.dataset.action}/confirm`,{method:'POST',body:JSON.stringify({actor:'C1001'})});b.textContent=d.status==='pending_review'?'已进入审核':'执行成功';toast(d.message);updateBadge()}catch(e){b.disabled=false;toast(e.message)}}
function stepSummary(step){const o=step.output||{};if(step.order===1)return `${o.level1||'-'} / ${o.level2||'-'} · ${((o.confidence||0)*100).toFixed(0)}%`;if(step.order===2)return `${o.name||'-'} · ${o.id||'-'}`;if(step.order===3)return `${(o.required_object_types||[]).length} 类对象 · ${(o.unresolved_object_types||[]).length} 类待读取`;if(step.order===4)return `${(o.calls||[]).length} 个 Function · ${(o.object_refs||[]).length} 个对象引用`;if(step.order===5)return `${o.evidence_count||0} 条有版本证据`;if(step.order===6)return `${o.decision||'-'} · ${(o.matched_rules||[]).length} 条规则命中`;if(step.order===7)return o.response||'回答已生成';return '执行完成'}
function renderTrace(d){$('#traceEmpty').style.display='none';$('#traceId').textContent=d.trace_id;const steps=d.decision_steps||[];$('#traceBody').innerHTML=steps.map((x,i)=>`<div class="step done" data-step="${i}" role="button" tabindex="0"><b>${x.order||i+1}</b><div><strong>${esc(x.name)}</strong><small>完成 · ${esc(x.duration_ms)}ms</small><p>${esc(stepSummary(x))}</p></div></div>`).join('')}

function decisionDetail(index){
  const d=state.lastDecision,p=state.preview,q=state.currentQuery,actual=d?.decision_steps?.[index];
  if(actual)return {...actual,trace_id:d.trace_id,summary:stepSummary(actual)};
  const pending=!d;
  const base={query:q,status:pending?(index===0?'previewed':'waiting'):'completed',trace_id:d?.trace_id||'预识别阶段'};
  const details=[
    {title:'意图识别',owner:'Mock Intent Model',version:'mock-intent-model:v1',summary:pending?(p?`${p.intent.level1} / ${p.intent.level2}`:'等待输入'):`${d.intent.level1} / ${d.intent.level2}`,payload:pending?p?.intent:d?.intent},
    {title:'绑定业务能力',owner:'Ontology Resolver',version:`catalog:v${state.catalog?12:'-'}`,summary:pending?(p?`${p.capability.name} · ${p.capability.id}`:'等待意图'):`${d.capability.name} · ${d.capability.id}`,payload:pending?p?.capability:d?.capability},
    {title:'读取业务对象',owner:'Object Resolver',version:'schema:v1',summary:pending?'提交后解析业务实体':`${d.capability.required_objects.length} 类对象，${d.object_refs.length} 个显式引用`,payload:pending?{expected_objects:[]}:{required_objects:d.capability.required_objects,object_refs:d.object_refs}},
    {title:'执行 Functions',owner:'Mock Tool Gateway',version:'mock-tools:v1',summary:pending?'提交后调用只读工具':`${d.tool_results.length} 个 Function 已完成`,payload:pending?[]:d.tool_results},
    {title:'检索证据',owner:'Mock Knowledge Adapter',version:'mock-rag:v1',summary:pending?'限定对象范围后检索':`${d.evidence.length} 条有版本证据`,payload:pending?[]:d.evidence},
    {title:'规则与风险',owner:'Policy Engine',version:'rules:v1',summary:pending?'等待对象与证据':`${d.risk} · ${d.action?(d.action.review_required?'强制人工审核':'需要用户确认'):'允许自动响应'}`,payload:pending?{rules:state.catalog?.rules||[]}:{risk:d.risk,action:d.action,rules:state.catalog?.rules||[]}},
    {title:'生成响应',owner:'Mock LLM',version:'mock-llm:v1',summary:pending?'等待前置节点完成':d.response,payload:pending?{}:{response:d.response,evidence_ids:d.evidence.map(x=>x.id),action_id:d.action?.id||null}}
  ];
  return {...base,...details[index]};
}
function openDecision(index){const x=decisionDetail(index),modal=$('#decisionModal'),total=state.lastDecision?.decision_steps?.length||7,isActual=Boolean(x.input&&x.output);$('#decisionDetailTitle').textContent=x.name||x.title;$('#decisionDetailBody').innerHTML=`<div class="detail-status"><span>${esc(x.trace_id)}</span><b>${esc(x.status)}</b></div><div class="detail-summary"><div><small>执行主体</small><strong>${esc(x.owner)}</strong></div><div><small>运行版本</small><strong>${esc(x.version)}</strong></div><div><small>节点序号 / 耗时</small><strong>${index+1} / ${total}${x.duration_ms?` · ${esc(x.duration_ms)}ms`:''}</strong></div><div><small>当前结论</small><strong>${esc(x.summary)}</strong></div></div><div class="detail-section"><h3>节点说明</h3><p>${esc(x.description||['对用户表达进行分类并保留候选意图。','根据意图映射稳定的业务能力契约。','解析本轮所需对象类型与实体引用。','通过受控 Function 读取源系统事实。','在对象限定范围内检索可引用证据。','执行确定性规则，计算风险与 Action 边界。','基于事实和证据生成最终用户响应。'][index])}</p></div><div class="detail-section"><h3>决策输入</h3><pre>${esc(JSON.stringify(isActual?x.input:{query:x.query},null,2))}</pre></div><div class="detail-section"><h3>决策输出</h3><pre>${esc(JSON.stringify(isActual?x.output:x.payload,null,2))}</pre></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function closeDecision(){const m=$('#decisionModal');m.classList.remove('open');m.setAttribute('aria-hidden','true')}
$('#traceBody').addEventListener('click',e=>{const step=e.target.closest('.step[data-step]');if(step)openDecision(Number(step.dataset.step))});
$('#traceBody').addEventListener('keydown',e=>{const step=e.target.closest('.step[data-step]');if(step&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openDecision(Number(step.dataset.step))}});
$('#closeDecision').onclick=closeDecision;$('.modal-backdrop').onclick=closeDecision;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDecision()});

async function updateBadge(){const r=await api('/api/reviews');$('#badge').textContent=r.filter(x=>x.status==='pending').length}
async function loadReviews(){const rows=await api('/api/reviews');$('#badge').textContent=rows.filter(x=>x.status==='pending').length;$('#reviewRows').innerHTML=rows.length?rows.map(r=>`<tr data-review="${r.id}"><td><b class="${r.risk}">${r.priority}</b></td><td>${esc(r.query)}</td><td>${esc(r.intent.level2)} · <b class="${r.risk}">${r.risk}</b></td><td>${esc(r.action.label)}</td><td><span class="status">${r.status}</span></td></tr>`).join(''):'<tr><td colspan="5"><div class="empty"><p>暂无记录。在聊天端输入“我要投诉门店态度很差”即可创建。</p></div></td></tr>';$$('[data-review]').forEach(el=>el.onclick=()=>showReview(rows.find(x=>x.id===el.dataset.review)))}
function showReview(r){$('#reviewDetail').innerHTML=`<small class="eyebrow">${r.priority} REVIEW</small><h3>${esc(r.action.label)}</h3><p>${esc(r.query)}</p><div class="detail"><div><small>识别意图</small>${esc(r.intent.level1)} / ${esc(r.intent.level2)}</div><div><small>风险与权限</small>${r.risk} · ${esc(r.action.required_permission)}</div><div><small>前置校验</small>${esc(r.action.preconditions.join('；'))}</div><div><small>失败补偿</small>${esc(r.action.compensation)}</div></div>${r.status==='pending'?`<div class="review-actions"><button class="reject" data-decision="rejected">驳回</button><button class="approve" data-decision="approved">批准执行</button></div>`:`<span class="status">${r.status}</span>`}`;$$('[data-decision]').forEach(b=>b.onclick=async()=>{await api(`/api/reviews/${r.id}/decision`,{method:'POST',body:JSON.stringify({decision:b.dataset.decision,actor:'agent-001',note:'演示审核'})});toast(b.dataset.decision==='approved'?'已批准并执行':'已驳回');loadReviews()})}
$('#refreshReviews').onclick=loadReviews;

async function loadCatalog(){if(!state.catalog)state.catalog=await api('/api/catalog');const c=state.catalog;$('#intentCount').textContent=c.intents.length;$('#objectCount').textContent=c.object_types.length;$('#capCount').textContent=c.capabilities.length;$('#ruleCount').textContent=c.rules.length;renderCatalog()}
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tab=b.dataset.tab;renderCatalog()});
function renderCatalog(){const c=state.catalog;let rows=[];if(state.tab==='intents')rows=c.intents.map(x=>({key:x.id,name:x.level2,sub:x.level1,meta:x.capability_id,risk:x.risk,raw:x}));if(state.tab==='objects')rows=c.object_types.map(x=>({key:x.id,name:x.label,sub:x.source,meta:`${x.properties.length} 属性`,raw:x}));if(state.tab==='capabilities')rows=c.capabilities.map(x=>({key:x.id,name:x.name,sub:x.description,meta:`${x.functions.length} Functions`,raw:x}));if(state.tab==='rules')rows=c.rules.map(x=>({key:x.id,name:x.name,sub:x.condition,meta:`P${x.priority}`,raw:x}));$('#catalog').innerHTML=rows.map((x,i)=>`<div class="catalog-item" data-config="${i}"><code>${esc(x.key)}</code><div><strong>${esc(x.name)}</strong><small> · ${esc(x.sub)}</small></div><span>${esc(x.meta)}</span><b class="${x.risk||''}">${x.risk||''}</b></div>`).join('');$$('[data-config]').forEach(el=>el.onclick=()=>showConfig(rows[+el.dataset.config]))}
function showConfig(x){$('#configDetail').innerHTML=`<small class="eyebrow">CONFIGURATION</small><h3>${esc(x.name)}</h3><p>${esc(x.sub)}</p><div class="detail"><div><small>配置标识</small>${esc(x.key)}</div><div><small>发布状态</small>published · version 1</div><div><small>运行依赖</small>${esc(x.meta)}</div></div><pre class="config-code">${esc(JSON.stringify(x.raw,null,2))}</pre>`}
$('#publish').onclick=async()=>{const d=await api('/api/config/publish',{method:'POST',body:JSON.stringify({actor:'product-admin',change:'演示配置发布'})});$('#version').textContent=d.version;toast(`配置 v${d.version} 已发布`)};

async function loadOps(){const [m,a]=await Promise.all([api('/api/metrics'),api('/api/audits')]);const cards=[['对话消息',m.conversations,'本次启动'],['意图准确率',`${(m.intent_accuracy*100).toFixed(1)}%`,'Mock 评估集'],['自动化率',`${(m.automation_rate*100).toFixed(1)}%`,'只读与低风险'],['待审核',m.pending_reviews,'L4 / 异常']];$('#metrics').innerHTML=cards.map(x=>`<article><small>${x[0]}</small><b>${x[1]}</b><span>${x[2]}</span></article>`).join('');$('#audits').innerHTML=a.length?a.map(x=>`<div class="audit"><time>${new Date(x.created_at).toLocaleTimeString()}</time><strong>${esc(x.event)}</strong><code>${esc(JSON.stringify(x.detail))}</code></div>`).join(''):'<div class="empty"><p>运行一轮对话后将生成审计链。</p></div>';const services=['意图模型','对象数据服务','知识检索','大模型生成','Action Gateway'];$('#health').innerHTML=services.map((x,i)=>`<div class="health-row"><i></i><span>${x}</span><b>Mock · ${18+i*6}ms</b></div>`).join('')}
$('#refreshOps').onclick=loadOps;
async function initialize(){const status=$('#runtimeStatus');try{await api('/api/health');status.classList.remove('offline');status.querySelector('span').textContent='Runtime 正常';await Promise.all([updateBadge(),loadCatalog()])}catch(e){status.classList.add('offline');status.querySelector('span').textContent='Runtime 未连接';addError(e.message)}}
initialize();
